Repository 1chooo/portfolio, pull requests merged in 2024-09, with the labels that each got.

#165 Fix/#163
  src/components/resume/timeline-item.tsx
  src/tests/components/resume/timeline-item.test.tsx
Labels: bug, size:xs

#169 chore(deps): bump @1chooo-com from 0.0.9 to 0.0.10
  package-lock.json
  package.json
Labels: dependencies

#170 refactor(style): make anchor tag inline (#164)
  src/app/globals.css
  src/components/side-bar/contact-list.tsx
  src/components/side-bar/social-list.tsx
  src/styles/nav-bar.css
  src/styles/resume/download-cv.css
  src/styles/resume/timeline-item.css
  src/styles/side-bar/contact-list.css
Labels: enhancement, UI, size:s

#181 refactor(layout): remove duplicated Google Analytics Scripts (#180)
  apps/web/src/app/layout.tsx
Labels: enhancement, size:xs

#184 fix(eslint): enable Jest globals (#183)
  apps/web/.eslintrc.js
Labels: size:xs

#192 Feature/#185
  apps/web/src/app/robots.ts
  apps/web/src/app/sitemap.ts
Labels: enhancement, size:m

#193 feat(docs): init Nextra documentation pages and theme configuration (#120)
  apps/docs/app/favicon.ico
  apps/docs/app/fonts/GeistMonoVF.woff
  apps/docs/app/fonts/GeistVF.woff
  apps/docs/app/globals.css
  apps/docs/app/layout.tsx
  apps/docs/app/page.module.css
  apps/docs/app/page.tsx
  apps/docs/next.config.mjs
  apps/docs/package.json
  apps/docs/pages/index.mdx
  apps/docs/pages/thanks.mdx
  apps/docs/public/favicon.ico
  apps/docs/public/file-text.svg
  apps/docs/public/globe.svg
  apps/docs/public/logo192.png
  apps/docs/public/logo512.png
  apps/docs/public/next.svg
  apps/docs/public/vercel.svg
  apps/docs/public/window.svg
  apps/docs/theme.config.tsx
  package-lock.json
Labels: documentation, enhancement, size:l

#199 chore(utils): update import paths for utility functions (#167)
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/portfolio/page.tsx
  apps/web/src/components/blog/filter-list.tsx
  apps/web/src/components/blog/filter-select-box.tsx
  apps/web/src/components/portfolio/filter-list.tsx
  apps/web/src/components/portfolio/filter-select-box.tsx
  apps/web/src/components/portfolio/projects.tsx
  apps/web/src/config/blog.ts
  apps/web/src/lib/utils/dom-utils.ts
  apps/web/src/lib/utils/filter-utils.ts
  apps/web/src/lib/utils/sort-blogs-by-date.ts
  apps/web/src/tests/sort-blogs-by-date.test.ts
Labels: enhancement, refactor, size:m

#204 Docs/#200
  README.md
  apps/docs/pages/_meta.json
  apps/docs/pages/code-walkthrough.mdx
  apps/docs/pages/contributing.mdx
  apps/docs/pages/index.mdx
  apps/docs/pages/user-guide.mdx
  apps/docs/public/images/cover.png
  apps/docs/public/images/cover_transparent_bg.png
  apps/web/docs/README.md
  apps/web/docs/changelog/v0.0.1.md
  apps/web/docs/changelog/v0.0.10.md
  apps/web/docs/changelog/v0.0.2.md
  apps/web/docs/changelog/v0.0.3.md
  apps/web/docs/changelog/v0.0.4.md
  apps/web/docs/changelog/v0.0.5.md
  apps/web/docs/changelog/v0.0.6.md
  apps/web/docs/changelog/v0.0.7.md
  apps/web/docs/changelog/v0.0.8.md
  apps/web/docs/changelog/v0.0.9.md
Labels: documentation, size:m

#206 refactor(about): extract SubHeader from introduction (#205)
  apps/web/src/app/page.tsx
  apps/web/src/components/about/about-text.tsx
Labels: enhancement, refactor, about, size:s

#208 Feature/#207
  apps/web/src/components/markdown/markdown-renderer.tsx
  apps/web/src/config/resume.ts
  apps/web/src/styles/resume/timeline-item.css
Labels: enhancement, UI, size:s

#210 chore(deps): bump @1chooo-com from 0.0.12 to 0.0.13
  apps/web/package.json
  package-lock.json
Labels: dependencies, size:xs

#222 Feature/#221
  apps/web/src/components/markdown/markdown-renderer.tsx
  apps/web/src/styles/about/about-text.css
Labels: UI, blog, size:s

#224 style(resume): update custom styling for ordered and unordered lists (#223)
  apps/web/src/styles/resume/timeline-item.css
Labels: enhancement, UI, resume, size:s

#227 Fix/#225
  apps/web/src/components/markdown/code-block.tsx
  apps/web/src/contents/2181-merge-nodes-in-between-zeros.md
Labels: enhancement, UI, size:s, new post

#228 git commit -m "chore(deps): bump @1chooo-com from 0.0.13 to 0.0.14"
  apps/web/package.json
  package-lock.json
Labels: dependencies, size:xs

#231 feat(markdown): update image tag
  apps/docs/pages/wiki.mdx
  apps/web/src/app/post/page.tsx
  apps/web/src/components/markdown/markdown-image.tsx
  apps/web/src/components/markdown/markdown-renderer.tsx
Labels: bug, documentation, refactor, blog, size:l

#234 chore(deps): bump @1chooo-com from 0.0.14 to 0.0.15
  apps/web/package.json
  package-lock.json
Labels: dependencies, size:xs

#235 refactor(blog): change the mock `post` router to the real `blog` router (#189)
  apps/web/src/app/blog/[slug]/page.tsx
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/post/page.tsx
Labels: blog, size:s

#238 Fix/#236
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/sitemap.ts
Labels: bug, enhancement, blog, size:s

#240 Feature/#239
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/globals.css
  apps/web/src/components/blog/filter-list.tsx
  apps/web/src/components/blog/filter-select-box.tsx
  apps/web/src/contents/example.mdx
Labels: enhancement, blog, size:m

#242 chore(deps): bump @1chooo-com from 0.1.0 to 0.1.1
  apps/web/package.json
  package-lock.json
Labels: dependencies, size:xs

#244 feat(nav-bar): improve blog active detected logic (#243)
  apps/web/src/components/nav-bar/nav-bar.tsx
Labels: enhancement, UI, blog, size:s

#245 feat(blog): implement pagination for blog posts (#241)
  apps/web/src/app/blog/page.tsx
Labels: enhancement, UI, blog, size:m

#254 chore(deps): bump @1chooo-com from 0.1.1 to 0.1.2
  apps/web/package.json
  package-lock.json
Labels: dependencies

#256 Feature/improve blog UI
  apps/web/src/app/blog/page.tsx
  apps/web/src/components/markdown/markdown-image.tsx
  apps/web/src/components/markdown/markdown-renderer.tsx
  apps/web/src/contents/1382-balance-a-binary-search-tree.md
  apps/web/src/contents/1480-running-sum-of-1d-array.md
  apps/web/src/contents/1550-three-consecutive-odds.md
  apps/web/src/contents/1791-find-center-of-star-graph.md
  apps/web/src/contents/2181-merge-nodes-in-between-zeros.md
  apps/web/src/contents/say-goodbye-to-git-graph-in-vscode.md
Labels: enhancement, UI, blog, size:l, new post

#259 chore(deps): bump @1chooo-com from 0.1.2 to 0.1.3
  apps/web/package.json
Labels: dependencies

#260 Feature/#104
  apps/web/package.json
  apps/web/src/components/side-bar/footer.tsx
  apps/web/src/components/side-bar/index.tsx
  apps/web/src/styles/side-bar/footer.css
  apps/web/tailwind.config.ts
  package-lock.json
Labels: enhancement, UI, size:m

#262 Fix/side bar
  apps/web/src/app/globals.css
Labels: bug, UI, size:s

#263 chore(deps): bump @1chooo-com from 0.1.3 to 0.1.4
  apps/web/package.json
  package-lock.json
Labels: dependencies

#265 style(side-bar): update the styles of separate line (#264)
  apps/web/src/app/globals.css
  apps/web/src/components/side-bar/index.tsx
Labels: enhancement, UI, size:xs

#270 Chore/update footer posts banner
  apps/docs/pages/code-walkthrough.mdx
  apps/web/package.json
  apps/web/postcss.config.mjs
  apps/web/public/images/banner/1382-balance-a-binary-search-tree.png
  apps/web/public/images/banner/1480-running-sum-of-1d-array.png
  apps/web/public/images/banner/1550-three-consecutive-odds.png
  apps/web/public/images/banner/1791-find-center-of-star-graph.png
  apps/web/public/images/banner/2181-merge-nodes-in-between-zeros.png
  apps/web/public/images/banner/amazon-linux-2-install-docker.png
  apps/web/src/app/globals.css
  apps/web/src/components/side-bar/footer.tsx
  apps/web/src/contents/1382-balance-a-binary-search-tree.md
  apps/web/src/contents/1480-running-sum-of-1d-array.md
  apps/web/src/contents/1550-three-consecutive-odds.md
  apps/web/src/contents/1791-find-center-of-star-graph.md
  apps/web/src/contents/2181-merge-nodes-in-between-zeros.md
  apps/web/src/contents/amazon-linux-2-install-docker.md
  apps/web/tailwind.config.ts
  package-lock.json
Labels: documentation, enhancement, dependencies, UI, size:m

#271 chore(deps): bump @1chooo-com from 0.1.4 to 0.1.5
  apps/web/package.json
  package-lock.json
Labels: dependencies, size:xs

#275 Feature/new post and change log
  apps/docs/pages/_meta.json
  apps/docs/pages/change-log.mdx
  apps/web/public/images/banner/how-to-enable-word-wrap-mdx-files-in-vscode.png
  apps/web/public/images/posts/how-to-enable-word-wrap-mdx-files-in-vscode/after.png
  apps/web/public/images/posts/how-to-enable-word-wrap-mdx-files-in-vscode/before.png
  apps/web/public/images/posts/how-to-enable-word-wrap-mdx-files-in-vscode/toogle-word-wrap.png
  apps/web/src/contents/how-to-enable-word-wrap-mdx-files-in-vscode.md
Labels: documentation, size:m, new post

#281 Feature/new post
  apps/web/public/images/banner/500-commits-milestone-in-1chooo-com.png
  apps/web/public/images/banner/goodbye-react-create-app.png
  apps/web/public/images/banner/mac-install-nodejs-npm.png
  apps/web/public/images/banner/make-your-react-more-elegant-with-map.png
  apps/web/public/images/banner/move-shared-components-to-global-layout.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/500-commit-achieving.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/about.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/blog.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/contact.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/dependabot.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/ga.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/milestone.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/portfolio.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/readme.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/resume.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/tag.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/tests.png
  apps/web/public/images/posts/500-commits-milestone-in-1chooo-com/well-commits.png
  apps/web/public/images/posts/goodbye-react-create-app/create-react-app-v-5-0-1.png
  apps/web/public/images/posts/goodbye-react-create-app/start-a-new-react-project.png
  apps/web/src/app/blog/[slug]/page.tsx
  apps/web/src/contents/500-commits-milestone-in-1chooo-com.md
  apps/web/src/contents/goodbye-react-create-app.md
  apps/web/src/contents/how-to-enable-word-wrap-mdx-files-in-vscode.md
  apps/web/src/contents/mac-install-nodejs-npm.md
  apps/web/src/contents/make-your-react-more-elegant-with-map.md
  apps/web/src/contents/move-shared-components-to-global-layout.md
Labels: size:l, new post

#288 feat(google): Add Google Analytics component (#272)
  apps/web/src/components/google/ga.tsx
  apps/web/src/components/google/google-analytics.tsx
  apps/web/src/types/google.d.ts
Labels: enhancement

#290 chore(blog): move post mdx parser to lib (#289)
  apps/web/src/app/blog/[slug]/page.tsx
  apps/web/src/app/blog/page.tsx
  apps/web/src/lib/db/blog.ts
Labels: enhancement, blog, size:s

#291 Revert "chore(blog): move post mdx parser to lib (#289)"
  apps/web/src/app/blog/[slug]/page.tsx
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/db/blog.ts
Labels: bug

#292 Fix/#291
  apps/web/src/app/blog/[slug]/page.tsx
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/sitemap.ts
  apps/web/src/lib/db/blog.ts
Labels: bug, enhancement, size:s

#293 chore(deps): bump @1chooo-com from 0.1.5 to 0.2.0
  apps/docs/pages/change-log.mdx
  apps/web/package.json
  package-lock.json
Labels: dependencies

#296 Refactor/#203
  apps/web/src/app/page.tsx
  apps/web/src/app/post/page.tsx
  apps/web/src/app/resume/page.tsx
  apps/web/src/components/about/about-text.tsx
  apps/web/src/components/about/github-stats.tsx
  apps/web/src/components/about/life-styles.tsx
  apps/web/src/components/about/tech-stack.tsx
  apps/web/src/components/blog/blog-post-list.tsx
  apps/web/src/components/blog/blog-post.tsx
  apps/web/src/components/blog/pagination.tsx
  apps/web/src/components/nav-bar/nav-bar.tsx
  apps/web/src/components/posts/blog-post.tsx
  apps/web/src/components/resume/timeline.tsx
  apps/web/src/components/side-bar/social-list.tsx
  apps/web/src/config/about.ts
  apps/web/src/config/blog.ts
  apps/web/src/config/index.ts
  apps/web/src/config/nav-bar.ts
  apps/web/src/config/resume.ts
  apps/web/src/types/about.d.ts
  apps/web/src/types/config.d.ts
  apps/web/src/types/resume.d.ts
  apps/web/src/types/socail-media.d.ts
  apps/web/src/types/type-guards.ts
Labels: enhancement, size:l

#298 chore(deps): bump @1chooo-com from 0.2.0 to 0.2.1
  apps/docs/pages/change-log.mdx
  apps/web/package.json
  package-lock.json
Labels: dependencies

#305 feat(blog): limit blog post summary to two lines with ellipsis (#303)
  apps/web/src/app/globals.css
Labels: enhancement, UI

#310 chore(deps): bump @1chooo-com from 0.2.1 to 0.2.2
  apps/docs/pages/change-log.mdx
  apps/web/package.json
  package-lock.json
Labels: dependencies

#311 Fix/missing blog contents and footer
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/globals.css
  apps/web/src/components/side-bar/footer.tsx
Labels: bug

#314 feat(blog): add skeleton loader for blogs
  apps/docs/pages/thanks.mdx
  apps/web/src/app/blog/page.tsx
  apps/web/src/app/globals.css
  package-lock.json
Labels: enhancement, UI, blog

#319 chore(deps): bump @1chooo-com from 0.2.2 to 0.2.3
  apps/docs/pages/change-log.mdx
  apps/web/package.json
  package-lock.json
Labels: dependencies

#324 fix/#315-skeleton-frame-is-not-show-in-blog-page
  apps/web/src/app/blog/page.tsx
  apps/web/src/components/skeleton-loader.tsx
Labels: enhancement, UI, blog

#329 Refactor/#320
  apps/docs/pages/thanks.mdx
  apps/web/src/app/blog/[slug]/page.tsx
Labels: documentation, enhancement, blog

#331 chore(deps): bump @1chooo-com from 0.2.3 to 0.2.4
  apps/docs/pages/change-log.mdx
  apps/web/package.json
  package-lock.json
Labels: dependencies

#336 fix(layout): update Google Analytics import and image URLs (#334)
  apps/web/src/app/layout.tsx
Labels: bug

#338 refactor(avatar-box): integrate avatar path to config (#326)
  apps/web/src/components/side-bar/avatar-box.tsx
  apps/web/src/components/side-bar/side-bar-info.tsx
  apps/web/src/config/index.ts
  apps/web/src/types/config.d.ts
Labels: enhancement, UI

#342 Feature/#327
  apps/web/src/app/page.tsx
  apps/web/src/components/side-bar/avatar-box.tsx
  apps/web/src/components/side-bar/info-content.tsx
  apps/web/src/config/index.ts
  apps/web/src/types/about.d.ts
  apps/web/src/types/config.d.ts
Labels: enhancement, about

#345 chore(deps): bump @1chooo-com from 0.2.4 to 0.2.5
  apps/docs/next-env.d.ts
  apps/docs/package.json
  apps/web/package.json
  package-lock.json
Labels: dependencies
